import Vue from "vue";
const ECharts = () => import("vue-echarts/components/ECharts");
import "echarts/lib/component/tooltip";
import "echarts/lib/component/title";
import "echarts/lib/component/dataZoom";
import "echarts/lib/component/radar";
import "echarts/lib/chart/radar";
import "echarts/lib/chart/line";
import "echarts/lib/chart/pie";
import "echarts/lib/chart/bar";
Vue.component("Chart", ECharts);
